// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    // `prisma migrate reset` 後に自動でシード + FTS インデックスを再構築する。
    // seed.ts は通常通り Prisma 経由で INSERT するため、events の AFTER INSERT トリガが
    // 動き events_fts に行が積まれる。init-fts は念のためのリビルド (idempotent)。
    // `db:reset` 後に denormalized counter (Group.memberCount / Tag.usageCount 等) を
    // バックフィルする (data-model review Critical #2/#3/#5)。
    seed: "tsx prisma/seed.ts && tsx prisma/seed-test-user.ts && tsx scripts/init-fts.ts && tsx scripts/recalc-counters.ts",
  },
  datasource: {
    // CI など DATABASE_URL 未設定の環境では SQLite (file:./dev.db) を fallback とする。
    // `prisma migrate reset` 等は datasource.url を必須とするためここで保証する。
    url: process.env["DATABASE_URL"] ?? "file:./dev.db",
  },
});
