allowBuilds:
  '@parcel/watcher': set this to true or false
  '@prisma/engines': true
  '@sentry/cli': false
  '@swc/core': set this to true or false
  better-sqlite3: true
  esbuild: true
  less: set this to true or false
  nx: set this to true or false
  prisma: true
  sharp: true
  unrs-resolver: true
onlyBuiltDependencies:
  - sharp
  - unrs-resolver
  - "@prisma/engines"
  - esbuild
  - prisma
  - better-sqlite3
